let projects = [
  {
    name: "M&M Vet App",
    thumbText: "M&M",
    image1: "/public/M&M logo plain.png",
    image2: "/public/M&M veterinary clinic.gif",
    className: "mmVetApp",
    description:
      "A customer portal app for a fictional veterinary clinic with CRUD features.",
    buildTools: [
      "React",
      "TypeScript",
      "Custom API",
      "Node.js",
      "Express",
      "Axios",
      "MongoDB",
      "Firebase",
      "HTML",
      "CSS",
    ],
    liveSite: "https://mm-vet-app.web.app/",
    sourceCode: "https://github.com/kirkwood616/mm-vet-app-frontend",
  },
  {
    name: "Movie Hub",
    thumbText: "MH",
    image1: "/public/M&M logo plain.png",
    image2: "/public/M&M veterinary clinic.gif",
    className: "mmVetApp",
    description:
      "A movie database app where you can search, view & add movies to a watchlist.",
    buildTools: [
      "React",
      "TypeScript",
      "Web API",
      "Node.js",
      "Axios",
      "HTML",
      "CSS",
    ],
    liveSite: "https://kirkwood616.github.io/react-api-lab",
    sourceCode: "https://github.com/kirkwood616/react-api-lab",
  },
  {
    name: "Gif Sifter",
    thumbText: "GS",
    image1: "/public/M&M logo plain.png",
    image2: "/public/M&M veterinary clinic.gif",
    className: "mmVetApp",
    description: "React App utilizing GIPHY's API to search for GIF images.",
    buildTools: ["React", "TypeScript", "Web API", "Node.js", "HTML", "CSS"],
    liveSite: "https://kirkwood616.github.io/react-lab04",
    sourceCode: "https://github.com/kirkwood616/react-lab04",
  },
  {
    name: "Animal Memory Match",
    thumbText: "AMM",
    image1: "/public/M&M logo plain.png",
    image2: "/public/M&M veterinary clinic.gif",
    className: "mmVetApp",
    description: "A classic card matching memory game with an Animal theme.",
    buildTools: ["HTML", "CSS", "JavaScript"],
    liveSite: "https://kirkwood616.github.io/js-project-memory-game",
    sourceCode: "https://github.com/kirkwood616/js-project-memory-game",
  },
  {
    name: "SVG CSS Animation",
    thumbText: "SCA",
    image1: "/public/M&M logo plain.png",
    image2: "/public/M&M veterinary clinic.gif",
    className: "mmVetApp",
    description: "An exploration of animating an SVG with CSS keyframes.",
    buildTools: ["HTML", "CSS", "JavaScript"],
    liveSite: "https://kirkwood616.github.io/svg-css-animation01",
    sourceCode: "https://github.com/kirkwood616/svg-css-animation01",
  },
];

export default projects;
