let projects = [
  {
    name: "ComplexApp",
    thumbText: "CA",
    image1: "public/ca.png",
    image2: "public/ca-gif.gif",
    className: "ca",
    description: "A twitter-esque app for sharing & viewing thoughts & interacting with other users.",
    buildTools: ["React", "JavaScript", "API", "Node.js", "Express", "Axios", "MongoDB", "Heroku", "Bootstrap", "Socket.IO", "HTML", "CSS"],
    liveSite: "https://complexbuild.netlify.app/",
    sourceCode: "https://github.com/kirkwood616/complex-react-frontend",
  },
  {
    name: "M&M Vet App",
    thumbText: "M&M",
    image1: "public/M&M logo plain.png",
    image2: "public/M&M veterinary clinic.gif",
    className: "mmVetApp",
    description: "A customer portal app for a fictional veterinary clinic with CRUD features.",
    buildTools: ["React", "TypeScript", "Custom API", "Node.js", "Express", "Axios", "MongoDB", "Firebase", "HTML", "CSS"],
    liveSite: "https://mm-vet-app.web.app/",
    sourceCode: "https://github.com/kirkwood616/mm-vet-app-frontend",
  },
  {
    name: "Movie Hub",
    thumbText: "MH",
    image1: "public/mh.png",
    image2: "public/mh-gif.gif",
    className: "movieHub",
    description: "A movie database app where you can search, view & add movies to a watchlist.",
    buildTools: ["React", "TypeScript", "Web API", "Node.js", "Axios", "HTML", "CSS"],
    liveSite: "https://kirkwood616.github.io/react-api-lab",
    sourceCode: "https://github.com/kirkwood616/react-api-lab",
  },
  {
    name: "Gif Sifter",
    thumbText: "GS",
    image1: "public/gs.png",
    image2: "public/gs-gif.gif",
    className: "gifSifter",
    description: "React App utilizing GIPHY's API to search for GIF images.",
    buildTools: ["React", "TypeScript", "Web API", "Node.js", "HTML", "CSS"],
    liveSite: "https://kirkwood616.github.io/react-lab04",
    sourceCode: "https://github.com/kirkwood616/react-lab04",
  },
  {
    name: "My Thoughts",
    thumbText: "MT",
    image1: "public/mt.png",
    image2: "public/mt-gif.gif",
    className: "myThoughts",
    description: "React App for adding, viewing & deleting your personal thoughts.",
    buildTools: ["React", "TypeScript", "Node.js", "HTML", "CSS"],
    liveSite: "https://kirkwood616.github.io/react-lab02",
    sourceCode: "https://github.com/kirkwood616/react-lab02",
  },
  {
    name: "Animal Memory Match",
    thumbText: "AMM",
    image1: "public/amm.png",
    image2: "public/amm-gif.gif",
    className: "amm",
    description: "A classic card matching memory game with an Animal theme.",
    buildTools: ["HTML", "CSS", "JavaScript"],
    liveSite: "https://kirkwood616.github.io/js-project-memory-game",
    sourceCode: "https://github.com/kirkwood616/js-project-memory-game",
  },
  {
    name: "SVG CSS Animation",
    thumbText: "SCA",
    image1: "public/sca.png",
    image2: "public/sca-gif.gif",
    className: "sca",
    description: "An exploration of animating an SVG with CSS keyframes.",
    buildTools: ["HTML", "CSS", "JavaScript"],
    liveSite: "https://kirkwood616.github.io/svg-css-animation01",
    sourceCode: "https://github.com/kirkwood616/svg-css-animation01",
  },
];

export default projects;
